### ISSUE TITLE
ESERVERSTART: This error is thrown by the electrode-server module

### ISSUE THREAD

**Issue by Wei-Zou** [electrode-io/electrode-io.github.io#167] opened 2016-09-23 06:35 UTC
error after running `gulp dev`, and `http://localhost:3000/` says unable to connect.

```
webpack: bundle is now VALID.
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`

    ESERVERSTART
    
    This error is thrown by the electrode-server module
  
    There was an error starting the Hapi.js server
    Please check the output of the stack trace below and correct the error shown
    
    If you have followed this resolution step and you are still seeing an
    error, please file an issue on the electrode-server repository

    git+https://github.com/electrode-io/electrode-server.git
  
Unhandled rejection Error: Electrode Server register plugins timeout.  Did you forget next() in a plugin?
    at /Users/weizou/Development/my-electrode-app/node_modules/electrode-server/lib/electrode-server.js:115:20
    at /Users/weizou/Development/my-electrode-app/node_modules/hapi/lib/server.js:391:28
    at [object Object].module.exports.internals.Server._createCache.internals.Server.start.internals.Server.initialize.internals.Server._start.internals.Server.stop._invoke.internals.Server._invoke.next [as _invoke] (/Users/weizou/Development/my-electrode-app/node_modules/hapi/lib/server.js:403:16)
    at Object.callback (/Users/weizou/Development/my-electrode-app/node_modules/hapi/lib/server.js:383:22)
    at Immediate._onImmediate (/Users/weizou/Development/my-electrode-app/node_modules/podium/lib/index.js:165:37)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
[nodemon] clean exit - waiting for changes before restart
```

**Comment by jchip** [comment] 2016-09-23 07:02
see error message `Unhandled rejection Error: Electrode Server register plugins timeout.  Did you forget next() in a plugin?`

**Comment by ezralalonde** [comment] 2016-10-04 23:21
For what it's worth, I was experiencing this issue today while trying to deploy to Heroku, following the tutorial. The app would crash after successfully running `gulp build`, and failing on `node server/index.js`.

What fixed it for me was changing `config/default.js` to read:

`            "content": "./server/views/index-view"

Instead of:

            "content": {
              "module": "./server/views/index-view"
            }

After this change everything worked as expected. I hope this helps.

Cheers,
Ezra.

**Comment by ezralalonde** [comment] 2016-10-05 17:26
Joel has informed me that changing the `content` block disables server side rendering, which is a workaround for the real issue. The real issue was, for me at least, was that registering components was hitting the timeout, and my solution basically disabled the plugin. This causes server-side rendering to not happen, but the app doesn't crash.

A better solution is to increase the timeout, by entering:

```
  "electrode": {
    "registerPluginsTimeout": 100000
  },
```

At the top-level of the `config/default.json` file. The number `100000` was randomly chosen.

**Comment by ananavati** [comment] 2016-10-13 02:09
@ezralalonde thanks for finding the issue and fix quickly, closing this issue as its a duplicate of https://github.com/electrode-io/electrode-server/issues/7

**Closed by ananavati** 2016-10-13 02:09 UTC
Labels: bug, duplicate
