### ISSUE TITLE
01.1 What is Electrode - No explanation of Archetype

### ISSUE THREAD

**Issue by AlexG92** [electrode-io/electrode-io.github.io#61] opened 2016-09-16 23:13 UTC
```
The heart of the platform is Electrode Archetypes. It allows for standardized configurations/structure of the app and its associated react components, also ensures streamlined development and deployment.
```

My first question is than, what is an archetype?

Where do I go to find out WHAT it is?

Where do I go to find out everything it does

Where do I go to find out how to use it?

**Comment by tiffine-koch** [comment] 2016-09-20 19:17
Content added by @NicholasDunham.

**Comment by AlexG92** [comment] 2016-09-26 05:52
Sorry, opening this up again. Archetype does more than structure, it also lets us stamp the components to look the same and use same dependencies. It allows us to manage lots of components.

@jchip and @ananavati - do you guys think you can write about archetypes and everything it is, than we can ask @NicholasDunham for help on the clarity?

I think we should also put it in the glossary.

**Comment by ananavati** [comment] 2016-10-13 01:39
closing this issue as its a duplicate of https://github.com/electrode-io/electrode-io.github.io/issues/61

**Closed by ananavati** 2016-10-13 01:39 UTC
Labels: duplicate, enhancement
